Upgrade to latest Renci.SshNet
There have been frequent unit test failures with:

System.InvalidOperationException: Server string is null or empty

This issue was identified at:
https://sshnet.codeplex.com/workitem/1935

It was apparently fixed in changeset 40540.